name: build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        ZENDESK_DOMAIN: ${{ secrets.ZENDESK_DOMAIN }}
        ZENDESK_USERNAME: ${{ secrets.ZENDESK_USERNAME }}
        ZENDESK_PASSWORD: ${{ secrets.ZENDESK_PASSWORD }}
      run: go test -v ./...
